[project]
name = "shallow-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "triplethreading", email = "triplethreading@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "torch>=2.10.0",
]

[tool.maturin]
module-name = "shallow_learning._core"
python-packages = ["shallow_learning"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
